### ISSUE TITLE
Autotimer stopped adding new timers since a few days

### ISSUE THREAD

**Issue by klorinczi** [OpenPLi/enigma2-plugins#1016]
Hi,

Since a few days Autotimer stopped adding new timers.

Using: VU+ Duo 4K SE, Openpli v9.0, latest updates.

Why Autotimer does not add new timers?
How to fix it?
How can I debug this problem?

Please help!

Thanks,
Konrad

**Comment by klorinczi** [comment]
I found this in autotimer.log:

```
2024-11-18 17:35:30,311 - INFO - Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/twisted/internet/base.py", line 1423, in run

File "/usr/lib/python3.9/site-packages/twisted/internet/base.py", line 1433, in mainLoop

File "/usr/lib/python3.9/site-packages/twisted/internet/base.py", line 972, in runUntilCurrent

File "/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py", line 114, in _callFromThread

--- <exception caught here> ---
File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred

File "/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py", line 419, in parseTimer

builtins.SystemError: <built-in function eEPGCache_search> returned a result with an error set
```
